# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FPGA-Projects/lab6_vga/lab6_vga.srcs/sources_1/ip/dcm_25m/dcm_25m.xci
# IP: The module: 'dcm_25m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA-Projects/lab6_vga/lab6_vga.srcs/sources_1/ip/dcm_25m/dcm_25m_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_25m'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/FPGA-Projects/lab6_vga/lab6_vga.srcs/sources_1/ip/dcm_25m/dcm_25m.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_25m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/FPGA-Projects/lab6_vga/lab6_vga.srcs/sources_1/ip/dcm_25m/dcm_25m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_25m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/FPGA-Projects/lab6_vga/lab6_vga.srcs/sources_1/ip/dcm_25m/dcm_25m.xci
# IP: The module: 'dcm_25m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA-Projects/lab6_vga/lab6_vga.srcs/sources_1/ip/dcm_25m/dcm_25m_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_25m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/FPGA-Projects/lab6_vga/lab6_vga.srcs/sources_1/ip/dcm_25m/dcm_25m.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_25m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/FPGA-Projects/lab6_vga/lab6_vga.srcs/sources_1/ip/dcm_25m/dcm_25m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_25m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
