# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/FPGA-Projects/lab6_vga/lab6/xdc/display_vga.xdc

# IP: ip/logo_rom/logo_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==logo_rom || ORIG_REF_NAME==logo_rom} -quiet] -quiet
