# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/FPGA-Projects/lab6_vga/lab6_vga.cache/wt [current_project]
set_property parent.project_path E:/FPGA-Projects/lab6_vga/lab6_vga.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/FPGA-Projects/lab6_vga/lab6_vga.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/FPGA-Projects/lab6_vga/test7.coe
add_files e:/FPGA-Projects/lab6_vga/InnovationCollege.coe
add_files e:/FPGA-Projects/lab6_vga/InnovationCollege-1.coe
read_verilog -library xil_defaultlib {
  E:/FPGA-Projects/lab6_vga/lab6/sources/debounce.v
  E:/FPGA-Projects/lab6_vga/lab6/sources/vga_timing.v
  E:/FPGA-Projects/lab6_vga/lab6/sources/top_flyinglogo.v
}
read_ip -quiet E:/FPGA-Projects/lab6_vga/lab6_vga.srcs/sources_1/ip/logo_rom/logo_rom.xci
set_property used_in_implementation false [get_files -all e:/FPGA-Projects/lab6_vga/lab6_vga.srcs/sources_1/ip/logo_rom/logo_rom_ooc.xdc]

read_ip -quiet E:/FPGA-Projects/lab6_vga/lab6_vga.srcs/sources_1/ip/dcm_25m/dcm_25m.xci
set_property used_in_implementation false [get_files -all e:/FPGA-Projects/lab6_vga/lab6_vga.srcs/sources_1/ip/dcm_25m/dcm_25m_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA-Projects/lab6_vga/lab6_vga.srcs/sources_1/ip/dcm_25m/dcm_25m.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA-Projects/lab6_vga/lab6_vga.srcs/sources_1/ip/dcm_25m/dcm_25m_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/FPGA-Projects/lab6_vga/lab6/xdc/display_vga.xdc
set_property used_in_implementation false [get_files E:/FPGA-Projects/lab6_vga/lab6/xdc/display_vga.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_flyinglogo -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_flyinglogo.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_flyinglogo_utilization_synth.rpt -pb top_flyinglogo_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
